### ISSUE TITLE
Unable to download the latest iOS 18 beta simulator (cryptexDiskImage)

### ISSUE THREAD

**Issue by gongzhang** [timsutton/speedwagon#37]
Hello,

I'm trying to download the latest beta simulators that Apple just released, but it seems something has changed. Below is the error message I'm receiving.

```sh
speedwagon list
...
├───────────────────────────────────────┼─────────┼──────────┼──────────────────┼────────┤
│ iOS 18.0 beta Simulator Runtime       │ 18.0    │ 22A5282m │ cryptexDiskImage │ 8.5 GB │
├───────────────────────────────────────┼─────────┼──────────┼──────────────────┼────────┤
│ tvOS 18.0 beta Simulator Runtime      │ 18.0    │ 22J5290l │ cryptexDiskImage │ 4.2 GB │
├───────────────────────────────────────┼─────────┼──────────┼──────────────────┼────────┤
│ visionOS 2.0 beta Simulator Runtime   │ 2.0     │ 22N5252m │ cryptexDiskImage │ 8.2 GB │
├───────────────────────────────────────┼─────────┼──────────┼──────────────────┼────────┤
│ watchOS 11.0 beta Simulator Runtime   │ 11.0    │ 22R5284o │ cryptexDiskImage │ 4.2 GB │
└───────────────────────────────────────┴─────────┴──────────┴──────────────────┴────────┘
```

```sh
speedwagon download "iOS 18.0 beta Simulator Runtime"
Downloading ...
   0% |                                                                                                                                     | ( 0/ 0 B) [0s:0s]
panic: Head "": unsupported protocol scheme ""

goroutine 1 [running]:
github.com/timsutton/speedwagon/cmd.glob..func1(0x1400018a900?, {0x14000032380?, 0x1?, 0x1?})
        /Users/tsutton/git/speedwagon/cmd/download.go:70 +0x630
github.com/spf13/cobra.(*Command).execute(0x10533b000, {0x14000032350, 0x1, 0x1})
        /Users/tsutton/Development/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x640
github.com/spf13/cobra.(*Command).ExecuteC(0x10533b5c0)
        /Users/tsutton/Development/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x320
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/tsutton/Development/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/timsutton/speedwagon/cmd.Execute()
        /Users/tsutton/git/speedwagon/cmd/root.go:23 +0x24
main.main()
        /Users/tsutton/git/speedwagon/main.go:11 +0x20
```

**Comment by timsutton** [comment]
Yeah, unfortunately the changes with new simulators use an internal Apple system framework and the Pallas Apple service to fetch the simulator download. So it may be some time before (or if) the new simulator types can be supported in this tool :/

**Comment by timsutton** [comment]
Looking into it a bit more, it seems like since [ipsw](https://github.com/blacktop/ipsw) already has all the support for OTA fetching, that adding simulator support to ipsw makes more sense, and to sunset speedwagon.

**Comment by gongzhang** [comment]
@timsutton Thank for the detailed information! They also removed the _Export Disk Image_ command in Xcode 16.

Xcode 15
<img width="400" alt="image" src="https://github.com/timsutton/speedwagon/assets/4470629/8bb0b926-2403-43a0-9ad3-3b92ee465a2c">

Xcode 16
<img width="400" alt="image" src="https://github.com/timsutton/speedwagon/assets/4470629/66aae6f8-9f72-4437-bc3f-8b2721e8069d">

**Comment by gongzhang** [comment]
UPDATE: Just noticed that there is a simulator runtime export/import feature in Xcode 16.

https://developer.apple.com/documentation/xcode-release-notes/xcode-16-release-notes

<img width="500" alt="image" src="https://github.com/user-attachments/assets/7b925800-6cd3-4b54-9bd4-137b9b001afc">

**Comment by Rashcodeacademy** [comment]
Hi Sorry bro it seems it does not work for other ios simulators too, what you built was fantastic, 
Do you think it will work again?
